### ISSUE TITLE
Why doesn't forever work with node 0.6.19

### ISSUE THREAD

**Issue by Redsandro** [foreversd/forever#495]
I run forever on two servers, which still run the `node 0.6` branch. No problems. But on one of them, `forever` stopped working after a restart.

First:

```
info:   Forever restarted process(es):
data:       uid  command script                      forever pid   logfile                        uptime        
data:   [0] rypY node    /home/user/nodejs/etquote 3031    14419 /home/user/.forever/rypY.log 0:5:55:26.631 
```

Now:

```
user@server007:/usr/bin$ node --version
v0.6.19
user@server007:/usr/bin$ forever list

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module './daemon.v0.6.19'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/forever/node_modules/daemon/lib/daemon.js:12:11)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
user@server007:/usr/bin$ 
```

I read in other issues that a reinstall of `forever` causes the correct deamon to be installed. I tried that, but I got the same problem.

`node` was renamed to `nodejs` at some point in the repo so I added a symlink. Did that on the other server too. No problems there.

I have no idea what me or someone else or some update mechanism did to introduce this problem, and how I can fix this. Any suggestions?
