### ISSUE TITLE
Error when starting forever with winston 0.3.3 installed, but works with winston 0.2.11

### ISSUE THREAD

**Issue by shangaslammi** [foreversd/forever#95]
Starting forever with the command

./node_modules/forever/bin/forever start -p log -c coffee myapp.coffee results in the following error:

TypeError: Property 'defaultTransports' of object #<Object> is not a function
    at Object.<anonymous> (./node_modules/forever/bin/forever:111:9)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)
    at EventEmitter._tickCallback (node.js:126:26)

The error only occurs if winston 0.3.3 is installed under forever/node_modules. Forcing npm to install winston 0.2.11 resolves the issue.

Versions of all dependent packages when error occurs:

```
├─┬ forever@0.4.0 
│ ├── colors@0.5.0 
│ ├── daemon@0.3.0 
│ ├─┬ optimist@0.2.6 
│ │ └── wordwrap@0.0.1 
│ ├── timespan@2.2.0 
│ ├── vows@0.5.9 
│ └─┬ winston@0.3.3 
│   ├─┬ loggly@0.3.5 
│   │ └── request@1.9.9 
│   └── pkginfo@0.2.2
```
